### ISSUE TITLE
insert_final_newline is not working with vs2017

### ISSUE THREAD

**Issue by davidshen84** [madskristensen/EditorConfigLanguage#19] opened 2017-06-08 07:36 UTC
### Installed product versions
- Visual Studio: 2017 pro, 64bit
- This extension: 1.17.202

### Description
I have set:

    insert_final_newline = true

But it takes no effect.

### Steps to recreate
1. Create .editorconfig file
2. Add **insert_final_newline = true** in `[.*]` section
3. Edit file, remove final newline
4. Save file

### Current behavior
File saved, no newline inserted.

### Expected behavior
Newline should be inserted if there's no newline already.

*Note*: I also have ReSharper installed. I have ReShaprer's support to `editorconfig` feature turned off.

**Comment by madskristensen** [comment] 2017-06-08 15:13
This is not a bug in this extension but in Visual Studio's support for .editorconfig files, so I'm closing it here.
 
Perhaps @jasonmalinowski has some insights into this?

**Closed as completed by madskristensen** 2017-06-08 15:13 UTC

**Comment by davidshen84** [comment] 2017-06-09 03:16
So is it a known issue? a by-design behavior? Maybe we should put this in the *README* file?

**Comment by olegtk** [comment] 2017-06-12 22:34
@davidshen84, which specific version of VS you are using? This should be already supported in VS 2017 15.3 Preview builds.

**Comment by madskristensen** [comment] 2017-06-12 22:42
I should update the extension to reflect that

**Comment by davidshen84** [comment] 2017-06-13 03:36
Here what I get form my Visual Studio about dialog.

    Microsoft Visual Studio Professional 2017 
    Version 15.2 (26430.13) Release
    VisualStudio.15.Release/15.2.0+26430.13
    Microsoft .NET Framework
    Version 4.6.01038

    Installed Version: Professional

**Comment by olegtk** [comment] 2017-06-13 04:49
Yeah, that's 15.2.  It's documented in [VS 2017 Release Notes](https://www.visualstudio.com/en-us/news/releasenotes/vs2017-knownissues) that insert_final_newline and trim_trailing_whitespace are not yet supported. 
They are supported in VS 2017 15.3 release, which is currently available as Preview.

**Comment by markw-t** [comment] 2017-06-13 14:22
Thanks for posting Oleg

Sent from my Windows 10 phone
