### ISSUE TITLE
editorconfig file does nothing

### ISSUE THREAD

**Issue by kevonh** [madskristensen/EditorConfigLanguage#18] opened 2017-06-02 20:09 UTC
### Installed product versions
- Visual Studio: [example 2017 Professional]
- This extension: [example 1.1.21]

### Description
.editorconfig file does nothing

### Steps to recreate
1: Create new .Net ClassLibrary project
2: Add .editorconfig file (tried project level, solution level, etc.)
3: Add rule with : Error set 
4: Add code which breaks rule

### Current behavior
No error, no warning

### Expected behavior
Build error

**Comment by madskristensen** [comment] 2017-06-02 20:29
Did you close and reopen the .cs file? Changes made to .editorconfig files don't take affect until you reopen the .cs files

**Comment by kevonh** [comment] 2017-06-02 21:21
DOH!!  That was the issue. Thank you!

**Comment by kevonh** [comment] 2017-06-02 22:52
Why does a file need to be open in order for the rules to apply?  I added a bunch of rules I expected to be applied across the solution, but only get build warnings for files which are open.  I've saved, cleaned re-built, closed and re-opened Visual Studio.  

I would think it would be preferred if the rules applied even if the file were closed.

**Comment by madskristensen** [comment] 2017-06-05 14:48
Let's ask @jasonmalinowski 

This is not a bug in this language service extension, but in Visual Studio's handling of .editorconfig files, so closing issue here

**Closed as completed by madskristensen** 2017-06-05 14:48 UTC
